Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@mackah666 
rocketinsights
/
terraform-blog-sample-live
8
1
0
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
terraform-blog-sample-live/.github/workflows/dev-deploy.yml

Kevin Karwaski Add code/configs
Latest commit 9103630 on 22 Jan
 History
 0 contributors
47 lines (41 sloc)  1.07 KB
  
name: Dev Deploy

on:
  push:
    branches:
      - main
    paths:
      - "dev/**"

defaults:
  run:
    working-directory: dev

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-east-1
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies (Terraform/Terragrunt/kubectl)
      run: |
        brew tap rocketinsights/tgenv
        brew install tfenv tgenv kubectl
        tfenv install
        tgenv install
    - name: Setup infra modules deploy key
      run: |
        mkdir ~/.ssh
        echo "${{ secrets.INFRA_MODULES_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa github.com
    - name: Terragrunt plan-all
      run: |
        terragrunt plan-all
    - name: Terragrunt apply-all
      run: |
        terragrunt apply-all --terragrunt-non-interactive
Loading complete
